export enum VendorStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  BLACKLISTED = 'BLACKLISTED',
}

export enum WorkOrderStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  VERIFIED = 'VERIFIED',
}

export enum PaymentType {
  ADVANCE = 'ADVANCE',
  INTERIM = 'INTERIM',
  FINAL = 'FINAL',
}

export enum VendorCategory {
  MANPOWER = 'MANPOWER',
  MATERIALS = 'MATERIALS',
  ELECTRICAL = 'ELECTRICAL',
  PLUMBING = 'PLUMBING',
  CIVIL_WORKS = 'CIVIL_WORKS',
  CLEANING_SERVICES = 'CLEANING_SERVICES',
  SECURITY_SERVICES = 'SECURITY_SERVICES',
  EQUIPMENT_RENTAL = 'EQUIPMENT_RENTAL',
  TRANSPORTATION = 'TRANSPORTATION',
  OFFICE_SUPPLIES = 'OFFICE_SUPPLIES',
  HVAC = 'HVAC',
  LEGAL_SERVICES = 'LEGAL_SERVICES',
  FOOD_AND_BEVERAGE = 'FOOD_AND_BEVERAGE',
  LOGISTICS = 'LOGISTICS',
  CONSULTANCY = 'CONSULTANCY',
  CONTENT_WRITER = 'CONTENT_WRITER',
  PRINTING = 'PRINTING',
  CAST = 'CAST',
  WOOD_ENGRAVING = 'WOOD_ENGRAVING',
  HOTEL = 'HOTEL',
  SCRIPT_WRITING = 'SCRIPT_WRITING',
  GLASS_WORK = 'GLASS_WORK',
  DOP = 'DOP',
  CLIENT_REFERENCE = 'CLIENT_REFERENCE',
  CONSUMABLES = 'CONSUMABLES',
  KITCHEN_ESSENTIALS = 'KITCHEN_ESSENTIALS',
  MUSIC_DIRECTOR = 'MUSIC_DIRECTOR',
  CAR_INSURANCE = 'CAR_INSURANCE',
  STICKERS = 'STICKERS',
  TILES = 'TILES',
  RENT_ITEMS = 'RENT_ITEMS',
  CURTAIN_DRY_CLEANING = 'CURTAIN_DRY_CLEANING',
  STATIONARY = 'STATIONARY',
  CURTAIN_FIXING_CHARGES = 'CURTAIN_FIXING_CHARGES',
  OFFICE_PAINT = 'OFFICE_PAINT',
  MOBILE_PHONE_VENDOR = 'MOBILE_PHONE_VENDOR',
  BATA_BOYS = 'BATA_BOYS',
  REFRIGERATOR_ASSET = 'REFRIGERATOR_ASSET',
  CAKE_BAKERY = 'CAKE_BAKERY',
  FURNITURE = 'FURNITURE',
  TILES_WORKERS = 'TILES_WORKERS',
  WIFI_SERVICES = 'WIFI_SERVICES',
  IT_HARDWARE = 'IT_HARDWARE',
  TABLE_COATING = 'TABLE_COATING',
  TABLE_TOPS = 'TABLE_TOPS',
  CAMERA_RENT = 'CAMERA_RENT',
  AC_SERVICE_CHARGES = 'AC_SERVICE_CHARGES',
  SEAL = 'SEAL',
  INFRASTRUCTURE_MAINTENANCE = 'INFRASTRUCTURE_MAINTENANCE',
  UPS_SYSTEMS = 'UPS_SYSTEMS',
  ELECTRONIC_ITEMS = 'ELECTRONIC_ITEMS',
  CURTAIN = 'CURTAIN',
  ELECTRONIC = 'ELECTRONIC',
  WATER_PURIFICATION = 'WATER_PURIFICATION',
  OFFICE_CHAIRS = 'OFFICE_CHAIRS',
  DRONE = 'DRONE',
  AUDITORS_AND_CA = 'AUDITORS_AND_CA',
  CREW_MEMBER = 'CREW_MEMBER',
  OFFICE_ESSENTIALS = 'OFFICE_ESSENTIALS',
  GIFT_AND_SWEETS = 'GIFT_AND_SWEETS',
  CAMERA_LENSE = 'CAMERA_LENSE',
  DOOR_LOCKS_AND_KEYS = 'DOOR_LOCKS_AND_KEYS',
  PARTITION_WORK = 'PARTITION_WORK',
  PAINTER = 'PAINTER',
  TABLE_FRAMES = 'TABLE_FRAMES',
  LIGHTING = 'LIGHTING',
  COSTUMES = 'COSTUMES',
  ELECTRICAL_MATERIALS = 'ELECTRICAL_MATERIALS',
  IT_ITEMS = 'IT_ITEMS',
  DRIVER = 'DRIVER',
  SCAFFOLDING_RENT = 'SCAFFOLDING_RENT',
  OFFICE_RENT = 'OFFICE_RENT',
  CHAIR_RENT = 'CHAIR_RENT',
  RAW_MATERIALS = 'RAW_MATERIALS',
  VOICE_OVER_ARTIST = 'VOICE_OVER_ARTIST',
  TEXTILE = 'TEXTILE',
  DECORATION_ITEMS = 'DECORATION_ITEMS',
  WIFI = 'WIFI',
  CINEMATOGRAPHY = 'CINEMATOGRAPHY',
  BATTERY = 'BATTERY',
  DIRECTORS = 'DIRECTORS',
  GIFT = 'GIFT',
  TRAINING = 'TRAINING',
  CABINET_WORKS = 'CABINET_WORKS',
  HOME_RENT = 'HOME_RENT',
  FOOD = 'FOOD',
  MAKEUP_ARTIST = 'MAKEUP_ARTIST',
  ROOM_FRESHNERS = 'ROOM_FRESHNERS',
  TOILET_COMMODE = 'TOILET_COMMODE',
  GUEST_SWEET_GIFT = 'GUEST_SWEET_GIFT',
  WATER_TANK = 'WATER_TANK',
  CAMERA_EQUIPMENT = 'CAMERA_EQUIPMENT',
  MASTERMINDS_AI_BOT_LIST = 'MASTERMINDS_AI_BOT_LIST',
  TICKET_BOOKING = 'TICKET_BOOKING',
  BIOMETRIC = 'BIOMETRIC',
  STEEL_WATER_BOTTLE = 'STEEL_WATER_BOTTLE',
  EMPLOYEE_RELIEVING_GIFT = 'EMPLOYEE_RELIEVING_GIFT',
  COMPUTERS = 'COMPUTERS',
  PRODUCTION_ASSISTANT = 'PRODUCTION_ASSISTANT',
  PRODUCTION_AND_LIGHT_UNIT = 'PRODUCTION_AND_LIGHT_UNIT',
  CARPET_FIXING = 'CARPET_FIXING',
  ELECTRICIAN_SUPPORT = 'ELECTRICIAN_SUPPORT',
  DEEP_CLEANING = 'DEEP_CLEANING',
  DI_SERVICES = 'DI_SERVICES',
  CCTV = 'CCTV',
  INDUS_ENTREPRENEURS = 'INDUS_ENTREPRENEURS',
  OMADA_CLOUD_SERVICE = 'OMADA_CLOUD_SERVICE',
  FIRE_EXTINGUISHER = 'FIRE_EXTINGUISHER',
  IT_ADMINISTRATIVE_WORK = 'IT_ADMINISTRATIVE_WORK',
  AUDIO_RECORD = 'AUDIO_RECORD',
  CHAIRS = 'CHAIRS',
  INFLUENCER = 'INFLUENCER',
  PRINTER_REPAIRS = 'PRINTER_REPAIRS',
  FINANCE = 'FINANCE',
  PHOTOGRAPHY = 'PHOTOGRAPHY',
  CARPENTRY = 'CARPENTRY',
  SANITARY = 'SANITARY',
  GRANITE = 'GRANITE',
  BOX = 'BOX',
  TEMPERED_GLASS = 'TEMPERED_GLASS',
  SHELF = 'SHELF',
  ALUMINIUM_MESH = 'ALUMINIUM_MESH',
  GLASS_CLAMP = 'GLASS_CLAMP',
  TABLE_FRAME_WELDING = 'TABLE_FRAME_WELDING',
  DASH_CAM = 'DASH_CAM',
  VO = 'VO',
  OTHERS = 'OTHERS',
}

export enum VendorGSTStatus {
  YES = 'YES',
  NO = 'NO',
  APPLIED = 'APPLIED',
}

export enum VendorExperience {
  LESS_THAN_1_YEAR = 'LESS_THAN_1_YEAR',
  ONE_TO_THREE_YEARS = 'ONE_TO_THREE_YEARS',
  THREE_TO_FIVE_YEARS = 'THREE_TO_FIVE_YEARS',
  FIVE_PLUS_YEARS = 'FIVE_PLUS_YEARS',
}

export enum AccountType {
  SAVINGS = 'SAVINGS',
  CURRENT = 'CURRENT',
}

export enum VendorType {
  FREELANCER = 'FREELANCER',
  AGENCY = 'AGENCY',
  RETAIL_FABRICATION = 'RETAIL_FABRICATION',
  IT_SOFTWARE_SAAS = 'IT_SOFTWARE_SAAS',
  CONTRACT_EMPLOYEE = 'CONTRACT_EMPLOYEE',
  CONSULTANT_TRAINER = 'CONSULTANT_TRAINER',
  EVENT_PRODUCTION = 'EVENT_PRODUCTION',
  OTHER = 'OTHER',
}

export enum VendorService {
  BRANDING_DESIGN = 'BRANDING_DESIGN',
  PERFORMANCE_MARKETING = 'PERFORMANCE_MARKETING',
  SOCIAL_MEDIA_MANAGEMENT = 'SOCIAL_MEDIA_MANAGEMENT',
  VIDEO_PRODUCTION = 'VIDEO_PRODUCTION',
  PHOTOGRAPHY = 'PHOTOGRAPHY',
  CONTENT_WRITING = 'CONTENT_WRITING',
  WEB_DEVELOPMENT = 'WEB_DEVELOPMENT',
  APP_DEVELOPMENT = 'APP_DEVELOPMENT',
  UI_UX = 'UI_UX',
  PRINTING_FABRICATION = 'PRINTING_FABRICATION',
  EVENTS_ACTIVATIONS = 'EVENTS_ACTIVATIONS',
  IT_INFRASTRUCTURE = 'IT_INFRASTRUCTURE',
  SOFTWARE_SAAS = 'SOFTWARE_SAAS',
  STAFFING_RESOURCES = 'STAFFING_RESOURCES',
  OTHER = 'OTHER',
}

export interface BankDetail {
  accountName: string;
  accountNumber: string;
  ifscCode: string;
  bankName: string;
  branchName: string;
  accountType: AccountType;
}

export interface VendorFormData {
  name: string;
  legalName: string;
  yearOfEstablishment?: string;
  natureOfBusiness?: string;
  vendorTypes: VendorType[];
  otherVendorType?: string;
  category: VendorCategory;
  otherCategory?: string;
  contactPerson: string;
  designation?: string;
  email: string;
  phoneNumber: string;
  alternateContactPerson?: string;
  alternateContactDetails?: string;
  addressLine1: string;
  addressLine2?: string;
  city: string;
  state: string;
  zipCode: string;
  country: string;
  panNumber: string;
  gstStatus: VendorGSTStatus;
  gstin?: string;
  isMsmeRegistered: boolean;
  msmeNumber?: string;
  servicesOffered: VendorService[];
  otherService?: string;
  serviceDescription?: string;
  industryExperience: VendorExperience;
  keyClients?: string;
  portfolioLink?: string;
  canSignNda: boolean;
  outsourcesWork: boolean;
  subcontractingDetails?: string;
  hasConflictOfInterest: boolean;
  isDeclared: boolean;
  authorizedSignatoryName: string;
  panCard?: File | null;
  gstCertificate?: File | null;
  portfolio?: File | null;
  bankProof?: File | null;
  otherDocuments?: File | null;
  bankDetail: BankDetail;
}
